### PR TITLE
build Sailfish app with static plugins as for IOS

### PR DESCRIPTION
**Pull request by janbar**
To get rid of warnings and double process on start I build the app in one
piece of cake. The generated binary is called 'noson'.

This change will work only with the latest sources of the app, because the
project configuration has been updated to manage the setting QT_STATICPLUGIN
for the Sailfish build.

### CODE REVIEW

**Comment by piggz** [comment]
I guess this means no need for a separate lib package anymore?  Might make it possible to get into harbour eventually.  Out of interest, how do you want to go about distributing it, do you want to set yourself up on openrepos, or just leave it to me?  Working on alarm dialog atm.

**Comment by janbar** [comment]
I leave it to you. You are the responsive of the port ;-).
Also no need separate lib any more. All c++ plugins are now static (NosonApp, NosonThumbnailer, NosonMediaScanner). I started to move all icons to the Sailfish standard and I have few issues as the pullup/pulldown menu on the page Services. that breaks the flick of the content. Oddly this issue doesn't occur in other pages :-/. Also we have to find a way to make the drag working (in the queue that works to move track but no way to add a context menu i.e to remove a track).
I will try to register me on Telegram. I have a week free for christmas.
Thanks for your work.

**Comment by janbar** [comment]
Yo I found the issue about flicking in the services page. I can continue on more interesting thing about the app design.

**Comment by piggz** [comment]
dont for get my PR for the alarm dialog ;) .... btw, I added my soundcloud account, but nothing plays, just says "action can be performed". you know what that is?

**Comment by janbar** [comment]
Yo Adam, I merged your PR flr alarms. Thanks for the great works.

For your soundcloud account, have you configured your sonos devices with your account using the official app ? This stage is required to play uri with any services with credentials.
If this stage has been completed and nothing play more, I need a debug log. Don't hide the key and token which I need to test it. I will forget them once I fixed the issue. Also send the log file to my email, and don't post it in github which is public.

Finally we are near a final release for sfos. Still things to manage playlist and an issue about to reconnect the sonos on wakeup. You could update the icon of the app in openrepos with the new  included in the sources.

My email is jlbarriere68@gmail.com

Before merging in the master, I will squash the commits into a couple of commits. Also you missed to add your name in the copyright header of the sources files. I will add it if you re agreed. 

Le Dimanche 22 décembre 2019, Adam Pigg a écrit :
> dont for get my PR for the alarm dialog ;) .... btw, I added my soundcloud account, but nothing plays, just says "action can be performed". you know what that is?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/piggz/harbour-noson/pull/3#issuecomment-56828342

-- 
JLB

**Comment by janbar** [comment]
noson-128x128

**Comment by janbar** [comment]
About the key and token , they don't allow me to play something, but it allow me to browse the service with the app to see the URIs and flags returned by the service.

**Comment by piggz** [comment]
Ah, i didnt realise I had to add using the official sonos app, i'll do that first!

**Pull request merged**
