### PR TITLE
Clean build

### PR DESCRIPTION
**Pull request by janbar**
Few fixes to build the latest.

### CODE REVIEW

**Comment by piggz** [comment]
Should this go into master or sailfish?

**Comment by janbar** [comment]
I think master. It allows to build the latest noson-app.

**Comment by piggz** [comment]
Oh, ofcourse, i was mixing up with my noson-app repo!

**Comment by piggz** [comment]
For info, I build on the mer OBS server here https://build.merproject.org/package/show/home:piggz/libnoson

**Comment by janbar** [comment]
Yo, no longer need to build libnoson apart. I forced BUILD_SHARED_LIBS=OFF in the project since the release 4.0. So when the lib isn't found it build its embedded archive, and we are sure to have the latest (currently 2.2.0).

**Pull request merged**
